services:
  front:
    build:
      context: ./front
    container_name: mythica_front
    ports:
      - "3000:3000"
    depends_on:
      - back
    tty: true  # フロントエンドでttyを有効に

  back:
    image: cosmtrek/air
    # working_dir value has to be the same of mapped volume
    working_dir: /app
    ports:
      - 8080:8080
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=user
      - DB_NAME=database
    volumes:
      - ./back/:/app/

  db:
    image: postgres:15
    container_name: mythica_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=database
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db/initdb.d/:/docker-entrypoint-initdb.d/

volumes:
  postgres-data: